### ISSUE TITLE
iOS Watch App Development

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#103]
Story: 
It is develop iOS Watch App to mange your android phone. 

Acceptable Criteria:

- [x] please integrate /sendNotification api with brain backend
- [x] should implement page to set UUID , which comes from your android phone. 
- [x] call the api with UUID
- [x] should work with the functions - search contacts, search images. 

In advance: 
To manage android develop furthermore. There are few more challege there.

**Comment by posix4e** [comment]
For a later milestone it will be cool to imagine what a chat preview on watch should look like
