### ISSUE TITLE
Gaurdrails in chatting issue

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#12]
Code:
https://github.com/ttt246/Brain/blob/main/src/rising_plugin/risingplugin.py#L223

Use Case:
{
    "token": "test_token",
    "uuid": "test-uuid",
    "history": [{
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Who won the world series in 2020?"
        },
        {
            "role": "assistant",
            "content": "The Los Angeles Dodgers won the World Series in 2020."
        }
    ],
    "user_input": "Where was it played?",
    "model": "gpt-3.5-turbo"
}

**Comment by stackdev37** [comment]
@jupiter0913 When I typed "Can you help me to find a lost contact number?", it says json parsing error. 
Is it relative with that? I will thank you if you would figure it out. 



![Image](https://github.com/ttt246/Brain/assets/105904959/a395551a-3617-4bf0-a69d-92bad40fa1f0)

**Comment by jupiter0913** [comment]
There is some issue in JSON parsing module, so I fixed it.

**Comment by jupiter0913** [comment]
I have fixed issue when you type "Can you help me to find a lost contact number?".

**Comment by stackdev37** [comment]
I've confirmed
