### ISSUE TITLE
UI Part 2: Update something with readme

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#191]
Story: 
we have a great readme with well-designed logo and splash as well. 

Acceptable Criteria:

- [x] update ui with readme (logo, splash screen and etc) in android
- [x] update ui with readme (logo, chatting page and etc) in extension

Cc: @golden1831

**Comment by stackdev37** [comment]
If you would want any image assets, you can contact @golden1831

**Comment by neptune-web** [comment]
@stackdev37 
I updated UI in extension.
This ticket was fixed.

Thanks.
