### ISSUE TITLE
Planner

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#23]
**Acceptable Criteria:**
- should make automatic progress in background with 
https://babyagi-ui.vercel.app/
- google keep, tasks sync , cal
- apple reminder, notes, tasks , iCloud mail, cal
- cal.com/ calendly support 

User should easily be able to organize meetings wi the anyone , bot should handle all plans and booking

**Comment by stackdev37** [comment]
Let's build this functionality based on AutoGPT Planner and we can customize it. 
https://github.com/Significant-Gravitas/Auto-GPT-Plugins/tree/master/src/autogpt_plugins/planner

**Comment by stackdev37** [comment]
It takes  around 5 days.

**Comment by kottahrisak** [comment]
The response format: 
{
    "message": [
        "OK",
        "Request fulfilled, document follows"
    ],
    "result": {
        "program": "auto_task",
        "content": "/auto/autogpt_c40a09075d11940f_1688122021744"
    },
    "status_code": 200
}

**Comment by stackdev37** [comment]
Looks great! I think the auto achievement should be worked in an async. Please make it in thread to handle it. Thanks.
