### ISSUE TITLE
Thomas x Langchain collab

### ISSUE THREAD

**Issue by pooriaarab** [ttt246/Brain#256]
@thomasr37oss Heyy Thomas 👋,

Found out about your profile from Langchain discord. Got an OSS project: AI x Creator economy and looking for contributors. 

You interested?

**Comment by thomasr37oss** [comment]
Yes, I am very interested in it.

Best,
Thomas
***@***.*** ***@***.***>
+1 217 374 8105

**Comment by pooriaarab** [comment]
Message me on LinkedIn to chat more. 

I couldn't contact you

https://linkedin.com/in/pooriaarab
