### ISSUE TITLE
Extension: Select an item

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#32]
Story: 
User should be able to select an result on the page to go to the detail web page. 

Acceptable Criteria:

- [x] scrape all item details with its hyper link as a result of searching by user in the page
- [x] train them(scraped data) to get its vector data(embedding)
- [ ] go to the detail page with user's prompt. ex: select the item about {title}, blabla..

To: @neptune-web 
Cc: @posix4e @tukpsyche

**Comment by neptune-web** [comment]
- Step 1.
When a user is going to select an item on browser, brain sends response like below schema.
`{ program: "select_item_detail_info", content: "" }`

- Step 2.
After the response is sent to risingbrowser, risingbrowser scraps all hyper links and send all the items to brain like below schema.
```
{
    links: [{title: string, url: string}], //all links on the page
    prompt: string // user's prompt
}
``` 

- Step 3.
After the request in step 2 is analyzed by brain, brain sends response to risingbrowser.
`{ program: "select_item", content: "url that a user is going to select" }`

**Comment by stackdev37** [comment]
@peterluo3131 it was implemented in brain
