### ISSUE TITLE
Manage Configuration about some keys in phone

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#40]
Story:
Be cool if all that stuff was encoded in a config file on the phone. And a settings screen which requires you to put in a backend

Acceptable Criteria:

- [ ] manage all stuff in a config and encode them to pass to backend securely. 
- [ ] client(user) should be able to configure them in a setting screen. 
- [ ] it is passed to backend as an encrypted data.

**Comment by tukpsyche** [comment]
Prerequisite https://github.com/ttt246/Brain/issues/17
