### ISSUE TITLE
Planner Strategy 1: Alarm Management

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#56]
Story:
We should manage alarm with clock and it should be set up in android phone , and then should call a ring by the certain time. 

Acceptable Criteria: 

- [ ] Alarm Management in Android (Add, Update, Delete)
- [ ] Train its command and handle its prompt properly in Brain

Challenge: 
There are few different clocks in android and it is a little difficult to manage them with its Intent.

**Comment by stackdev37** [comment]
It takes around 4 days.

**Comment by stackdev37** [comment]
Please follow the blow steps to implement this function. 

1. call /sendNotificaiton with user's input (Android) and return its command(program: "alram_crud [create | delete | update | get]) as its response.
2. call /alarm/[your alarm api] with the list of alarms (Android) and return its detail information including id, title, dec, time etc as its response.


To: @peterluo3131 @jupiter0913

**Comment by peterluo3131** [comment]
This is alarm lists schema for update | delete | get.
{
    alarms: [{
        id: Int,
        time: String,
        enabled: boolean,
        label: String
    }],
    prompt: String
}

Please make response like below.
{
    status_code: Int,
    message: [],
    result: {
        program: "alarm_manage",
        content: {
            alarms: [{
                type: String,
                id: Int,
                time: String,
                label: String,
                enabled: boolean
            }]
        }
    }
}

**Comment by peterluo3131** [comment]
I've tried to get a list of alarms on device, but it's not possible. We can only schedule alarm. 😢 
To: @jupiter0913 @stackdev37 
Cc: @posix4e @tukpsyche
