### ISSUE TITLE
Implement/Upgrade Debug UI

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#86]
Story: 
Apart from swagger, it is web frontend page for developers or admin users to test something.

Acceptable Criteria:

- [x] upgrade the existing the debug ui for /sendNotification function. Make it more readable and friendly.

**Comment by posix4e** [comment]
What if we use gradio? It can integrate easily into fastapi.

**Comment by stackdev37** [comment]
That's fine!
