### ISSUE TITLE
LLM Strategy 3: Implement an interface to configure model

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#9]
Acceptable Criteria: 

- [ ] allow brain to choose between llama, falcon, gpt 3.5, gpt 4, autogpt
- [ ] create a custom autogpt that uses falcon and llama instead

**Comment by stackdev37** [comment]
@peterluo3131 we need to implement a setting configuration page in android application for different models (currently, we have gpt 3.5, 4, falcon-7b).

**Comment by stackdev37** [comment]
We need to include the below format for the all endpoints. 

{
"openAiKey": string, 
"pineconeKey": string, 
"firebaseKey": string, 
"settings": {
        "model": string (gpt-3-5, gpt-4, falcon, etc)
        "temperature": float
    }
}

**Comment by posix4e** [comment]
I’m not sure the client should include the model in v1. Openai could be
optional and we could fallback to captcha.

**Comment by stackdev37** [comment]
I think openai is mandatory for our project. That's why I see  GPT Model's evaluation has a strong positional bias in favor of the first response so it is the best to get user's behavior first.

**Comment by stackdev37** [comment]
We don't need to pass the model by client. I just updated the format.

**Comment by stackdev37** [comment]
Custom autogpt will be handed in nextsprint(next week)
