### ISSUE TITLE
Implement Email Management Component in Android

### ISSUE THREAD

**Issue by stackdev37** [ttt246/Brain#99]
Story: 
It is to manage emails with brain. The interfaces will be shared for android and others([Implement Email Management Interface in Brain#98](https://github.com/ttt246/Brain/issues/98))

Acceptable Criteria:
- [x] Develop email Component in ChatActivity

- [x] Integrate the email interfaces from brain.

**Comment by stackdev37** [comment]
It takes around 5 days.

**Comment by posix4e** [comment]
How far can we get with just the Gmail plugin in langchain?

**Comment by stackdev37** [comment]
Langchian gmail toolkit is also great and it is very general, whereas autogpt gmail plugin is focusing its special goals. 
So more useful with autogpt plugin. Of course, we need to customize something on it.
